// Aquí vas a poner tu array de productos

// Va un ejemplo, debería de verse así. Pongan sus propios objetos abajo.

// const arrayProductos = [
//     {
//         nombre: "1"
//     },
//     {
//         nombre: "2"
//     },
//     {
//         nombre: "3"
//     },
//     {
//         nombre: "4"
//     },
// ];

const arrayProductos = [
    {
        "img": "https://www.jbl.com.ar/dw/image/v2/AAUJ_PRD/on/demandware.static/-/Sites-masterCatalog_Harman/default/dw1a8b3552/JBL_Tune_Flex_Product_Image_Hero_White.png?sw=537&sfrm=png",
        "title": "JBL Tune Flex",
        "type": "headphone",
        "price": 145,
        "description": "Auriculares True Wireless con cancelación de ruido",
        "stock": 9,
        "full_desc_title": "Pure Bass. Cero ruidos.",
        "full_desc_content": "Afronta tu día canción a canción con los JBL Tune Flex. Los auriculares True Wireless te ofrecen hasta 32 horas de excepcional sonido JBL Pure Bass, mientras que su diseño ergonómico y resistente al agua te proporciona comodidad durante todo el día en cualquier clima. Un simple toque te permite gestionar y disfrutar de llamadas perfectas en cualquier lugar, sin ruidos ambientales. Y con la tecnología Active Noise Cancelling y Smart Ambient, tú eliges si quieres desconectar del mundo o relacionarte con tu entorno. El diseño de barra abierta garantiza una gran comodidad durante todo el día y un sonido natural. Y lo mejor de todo es que la Aplicación de los auriculares JBL te permite personalizar tu experiencia auditiva. Conecta con tu mundo a tu manera.",
    },
    {
        "img": "https://www.jbl.com.ar/dw/image/v2/AAUJ_PRD/on/demandware.static/-/Sites-masterCatalog_Harman/default/dw3fb2760d/1.JBL_Tour_Pro%202_Product%20Image_Hero_Black.png?sw=537&sfrm=png",
        "title": "JBL Tour Pro 2",
        "type": "headphone",
        "price": 382,
        "description": "Auriculares True Wireless con cancelación de ruido",
        "stock": 8,
        "full_desc_title": "True Adaptive Noise Cancelling",
        "full_desc_content": "La tecnología True Adaptive Noise Cancelling utiliza automáticamente 4 micrófonos de detección de ruido para ajustarse a tu entorno en tiempo real, minimizando las distracciones cuando necesites centrarte, optimizando el rendimiento de los JBL Tour Pro 2 para una experiencia de audio superior, todo con la capacidad de ajustar el control del modo ANC con la aplicación JBL Headphones.",
    },
    {
        "img": "https://www.jbl.com.ar/dw/image/v2/AAUJ_PRD/on/demandware.static/-/Sites-masterCatalog_Harman/default/dwebc87e02/JBL_TOUR_One%20M2_Product%20Image_Hero_Black.png?sw=537&sfrm=png",
        "title": "JBL Tour One M2",
        "type": "headphone",
        "price": 569,
        "description": "Auriculares supraaurales inalámbricos con cancelación de ruido",
        "stock": 5,
        "full_desc_title": "Smart Ambient",
        "full_desc_content": "Permanece atento a los sonidos que te rodean mientras disfrutas de tu música con Smart Ambient, controla los niveles del sonido ambiental y activa el botón de Amplificación Personal del Sonido a través de la aplicación JBL Headphones para aumentar el volumen de las conversaciones con +15-20dB y ajustar el balance L/R.",
    },
    {
        "img": "https://www.jbl.com.ar/dw/image/v2/AAUJ_PRD/on/demandware.static/-/Sites-masterCatalog_Harman/default/dw02643952/1.JBL_Wave_VIBE_100TWS_Product_Images_Hero_Ivory.png?sw=537&sfrm=png",
        "title": "JBL Wave 100TWS",
        "type": "headphone",
        "price": 70,
        "description": "Auriculares supraaurales True Wireless",
        "stock": 3,
        "full_desc_title": "Bajos profundos y mucha diversión",
        "full_desc_content": "Lleva tu sonido a todas partes. Con unos bajos que puedes sentir, hasta 32 horas de autonomía de la batería y un diseño seguro y cómodo, los auriculares JBL Wave Buds resistentes a las salpicaduras y al polvo están diseñados para tu entretenimiento diario. Tanto si paseas por las calles de la ciudad como si estás relajado en la playa, tus llamadas estéreo manos libres siempre serán nítidas, mientras que la tecnología Smart Ambient te mantiene al tanto de lo que te rodea. Y cuando necesites un impulso adicional, puedes acelerar la carga con dos horas adicionales de potencia en solo 10 minutos.",
    },
    {
        "img": "https://www.jbl.com.ar/dw/image/v2/AAUJ_PRD/on/demandware.static/-/Sites-masterCatalog_Harman/default/dwd241832a/1_JBL_PARTYBOX_110_HERO_x2.png?sw=537&sfrm=png",
        "title": "JBL Partybox 110",
        "type": "speaker",
        "price": 870,
        "description": "Altavoz para fiestas portátil con un potente sonido de 160W, con luces",
        "stock": 19,
        "full_desc_title": "Empieza la fiesta con un potente sonido y un juego de luces dinámico",
        "full_desc_content": "Lleva una dimensión totalmente nueva a cualquier fiesta con los exclusivos anillos de luces LED dinámicos, sincronizados con el potente sonido y los bajos profundos del PartyBox 110. Llévate el PartyBox dondequiera que vayas con el diseño a prueba de salpicaduras y conecta una guitarra y un micrófono para disfrutar de la experiencia inmersiva definitiva. Con un amplificador de bajos y el potente sonido JBL Original Pro, tus amigos no solo escucharán la música, sino que la sentirán durante 12 horas de reproducción para que la fiesta siga durante todo el día o la noche. Utiliza la aplicación PartyBox para tener un control total mientras transmites tus canciones de forma inalámbrica.",
    },
    {
        "img": "https://www.jbl.com.ar/dw/image/v2/AAUJ_PRD/on/demandware.static/-/Sites-masterCatalog_Harman/default/dw0cced459/JBL_AUTHENTICS_500_HERO_42813_x3.png?sw=537&sfrm=png",
        "title": "JBL Authentics 500",
        "type": "speaker",
        "price": 1350,
        "description": "Altavoz inteligente de alta fidelidad y diseño retro, con Wi-Fi y Bluethooth",
        "stock": 15,
        "full_desc_title": "Diseño retro y alto rendimiento con Dolby Atmos® Music",
        "full_desc_content": "Llena cualquier habitación con el mejor sonido de vanguardia y un llamativo estilo retro con el JBL Authentics 500. Desde su rejilla Quadrex hasta su receptáculo de piel personalizado, el altavoz se inspira en los icónicos diseños JBL de los años 70, actualizados para el siglo XXI con las últimas tecnologías de sonido y control. Sumérgete en un sonido realista de alta definición con Dolby Atmos® Music gracias a los altavoces de agudos de aluminio del Authentics 500 y al puerto de graves patentado SlipStream™. Con Google Assistant y Amazon Alexa disponibles simultáneamente, puedes reproducir tu música favorita, controlar tus dispositivos de casa inteligentes y mucho más, dejando las manos libres y usando solo tu voz.",
    },
    {
        "img": "https://www.jbl.com.ar/dw/image/v2/AAUJ_PRD/on/demandware.static/-/Sites-masterCatalog_Harman/default/dw4bc94fe7/JBL_CHARGE5_HERO_BLUE_0038_x3.png?sw=537&sfrm=png",
        "title": "JBL Charge 5",
        "type": "speaker",
        "price": 330,
        "description": "Altavoz portátitl resistente al agua con batería integrada",
        "stock": 20,
        "full_desc_title": "Reproducción y carga infinitas",
        "full_desc_content": "Lleva la fiesta contigo haga el tiempo que haga. El altavoz JBL Charge 5 ofrece el potente sonido JBL Original Pro gracias al driver optimizado de gran amplitud, el altavoz de agudos independiente y los dos radiadores de graves JBL. Hasta 20 horas de autonomía y una práctica batería integrada que te permite cargar tus dispositivos y alargar la fiesta durante toda la noche. ¿Llueve? ¿Has derramado la bebida? ¿Estás en la playa? El Charge 5 resiste al polvo y el agua conforme a la norma IP67 para aguantar lo que le eches. Además, podrás conectar varios altavoces JBL compatibles con PartyBoost para disfrutar de un sonido con potencia suficiente para una multitud. Sus colores totalmente nuevos, inspirados en las últimas tendencias de moda urbana, le dan un aspecto tan bueno como su sonido.",
    },
    {
        "img": "https://www.jbl.com.ar/dw/image/v2/AAUJ_PRD/on/demandware.static/-/Sites-masterCatalog_Harman/default/dwc2c5b0a4/JBL%20PULSE%205_06.png?sw=537&sfrm=png",
        "title": "JBL Pulse 5",
        "type": "speaker",
        "price": 375,
        "description": "Altavoz Bluetooth portátil con juego de luces",
        "stock": 11,
        "full_desc_title": "Un sonido que puedes sentir",
        "full_desc_content": "Ilumina el momento con el bonito y personalizable juego de luces de 360 grados del JBL Pulse 5 que se sincroniza con el ritmo de la música y el driver ascendente ofrece graves profundos y el sonido JBL Original Pro repartido en todas direcciones. La correa resistente te permite llevar este altavoz Bluetooth portátil, resistente al polvo y al agua, desde tu terraza hasta la playa y más allá. Baila hasta el amanecer con 12 horas de reproducción o utiliza la opción PartyBoost para emparejar varios altavoces compatibles cuando quieras aumentar el nivel de sonido y diversión.",
    },
    {
        "img": "https://www.jbl.com.ar/dw/image/v2/AAUJ_PRD/on/demandware.static/-/Sites-masterCatalog_Harman/default/dw6b1d398a/JBL_CINEMA_SB190_HERO.png?sw=537&sfrm=png",
        "title": "JBL Cinema SB190",
        "type": "home_theater",
        "price": 830,
        "description": "Barra de sonido de 2.1 canales con Virtual Dolby Atmos",
        "stock": 8,
        "full_desc_title": "Más bajos. Imponente sonido 3D",
        "full_desc_content": "Disfruta de un sonido envolvente y con la calidad de una sala de cine desde tu sofá. El JBL Cinema SB190 te ofrece unos increíbles bajos desde un altavoz de graves inalámbrico y los impresionantes efectos envolventes de Virtual Dolby Atmos. La conexión con un solo cable hace que la potente barra de sonido de perfil bajo sea muy fácil de configurar. Y, por supuesto, puedes reproducir tu música favorita directamente desde tu teléfono o tableta portátil. Pasa las palomitas y baja las luces, es noche de película.",
    },
    {
        "img": "https://www.jbl.com.ar/dw/image/v2/AAUJ_PRD/on/demandware.static/-/Sites-masterCatalog_Harman/default/dwf1ff9eed/JBL_QUANTUM%20ONE_Product%20Image_Angle.jpg?sw=270&sh=330&sm=fit&sfrm=png",
        "title": "JBL Quantum ONE",
        "type": "gamer",
        "price": 215,
        "description": "Auriculares integrales profesionales de gaming en PC on calbe USB",
        "stock": 13,
        "full_desc_title": "Sound is Survival",
        "full_desc_content": "Aporte épica a su juego. Los auriculares con cable JBL Quantum ONE ofrecen calidad profesional, sonido envolvente JBL QuantumSPHERE 360™ con seguimiento de cabeza mejorado y cancelación activa del ruido para gaming. Con un posicionamiento preciso del sonido, el sistema JBL Quantum SOUND Signature produce una curva inmersiva gracias a sus amplificadores de neodimio de 50 mm y alta definición. El micrófono vocal desmontable ofrece interacciones claras, supresión del ruido, funciones de silencio y un dial de ajuste de volumen con certificación DISCORD. Su diseño ligero y ergonómico le hará sentirse cómodo mientras que el sistema JBL QuantumENGINE ofrece opciones personalizables y perfiles de usuario. Los JBL Quantum ONE representan la vanguardia y el nivel de realismo virtual más profundo.",
    },
    {
        "img": "https://www.jbl.com.ar/dw/image/v2/AAUJ_PRD/on/demandware.static/-/Sites-masterCatalog_Harman/default/dwb316b694/1.JBL_Wave%20Flex_Product%20Image_Hero%2001_Black.png?sw=537&sfrm=png",
        "title": "JBL Wave Flex",
        "type": "headphone",
        "price": 130,
        "description": "Auriculares de botón True Wireless",
        "stock": 2,
        "full_desc_title": "Bajos profundos y mucha diversión",
        "full_desc_content": "Lleva tu sonido a todas partes. Con unos bajos que puedes sentir, hasta 32 horas de autonomía de la batería y un diseño seguro y cómodo, los auriculares JBL Wave Flex resistentes a las salpicaduras y al polvo están diseñados para tu entretenimiento diario. Tanto si paseas por las calles de la ciudad como si estás relajado en la playa, tus llamadas estéreo manos libres siempre serán nítidas, mientras que la tecnología Smart Ambient te mantiene al tanto de lo que te rodea. Y cuando necesites un impulso adicional, puedes acelerar la carga con dos horas adicionales de potencia en solo 10 minutos.",
    },
    {
        "img": "https://www.jbl.com.ar/dw/image/v2/AAUJ_PRD/on/demandware.static/-/Sites-masterCatalog_Harman/default/dwebd07052/1.JBL_TUNE_760NC_Product%20Image_Hero_White.png?sw=537&sfrm=png",
        "title": "JBL Tune 770NC",
        "type": "headphone",
        "price": 173,
        "description": "Auriculares circumaurales inalámbricos con con cancelación de ruido",
        "stock": 6,
        "full_desc_title": "Disfruta de tu música sin ruidos.",
        "full_desc_content": "Cuando tu música está encendida, nada más importa. Los auriculares inalámbricos JBL Tune 770NC con cancelación de ruido adaptativa cumplen esa promesa durante todo el día y más, al tiempo que te evitan los ruidos no deseados. Con una batería de 70 horas de duración, pasarás fácilmente una semana ajetreada utilizándolos y aún tendrás suficiente sonido JBL Pure Bass para pasar el fin de semana. Y si necesitas una carga rápida, 5 minutos te proporcionan 3 horas adicionales de música. Ligeros y plegables, los JBL Tune 770NC también pueden conectarse con dos dispositivos Bluetooth® simultáneamente, para que nunca pierdas una llamada mientras ves un vídeo en tu tableta. Descarga la aplicación gratuita JBL Headphones para adaptar el sonido a tus gustos. Las indicaciones de voz te guiarán en tu idioma a través de las funciones. Gestiona tus llamadas y tu asistente de voz sin problemas desde tu teléfono y utiliza VoiceAware para oírte cuando hables. Simplemente elige el color que mejor se adapte a tu esencia y comienza a divertirte.",
    },
    {
        "img": "https://www.jbl.com.ar/dw/image/v2/AAUJ_PRD/on/demandware.static/-/Sites-masterCatalog_Harman/default/dw74d4c863/1.JBL_Wave_Vibe_%20Buds_Product%20Image_Hero_Black.png?sw=537&sfrm=png",
        "title": "JBL Wave Buds",
        "type": "headphone",
        "price": 103,
        "description": "Auriculares de botón True Wireless",
        "stock": 0,
        "full_desc_title": "Bajos profundos y mucha diversión",
        "full_desc_content": "Lleva tu sonido a todas partes. Con unos bajos que puedes sentir, hasta 32 horas de autonomía de la batería y un diseño seguro y cómodo, los auriculares JBL Wave Buds resistentes a las salpicaduras y al polvo están diseñados para tu entretenimiento diario. Tanto si paseas por las calles de la ciudad como si estás relajado en la playa, tus llamadas estéreo manos libres siempre serán nítidas, mientras que la tecnología Smart Ambient te mantiene al tanto de lo que te rodea. Y cuando necesites un impulso adicional, puedes acelerar la carga con dos horas adicionales de potencia en solo 10 minutos.",
    },
    {
        "img": "https://www.jbl.com.ar/dw/image/v2/AAUJ_PRD/on/demandware.static/-/Sites-masterCatalog_Harman/default/dw310e02bc/T110_Blue_Hero-1606x1606px.png.png?sw=537&sfrm=png",
        "title": "JBL Tune 110",
        "type": "headphone",
        "price": 25,
        "description": "Auriculares intraaurales",
        "stock": 16,
        "full_desc_title": "Bajos listos para el rock and roll.",
        "full_desc_content": "Le presentamos los auriculares intraaurales JBL TUNE110. Son ligeros, cómodos y compactos. Dentro de la carcasa de auricular duradera, un par de unidades de 9 mm ofrecen bajos notables y reproducen el sonido Pure Bass de JBL que ha experimentado en salas de conciertos, pabellones y estudios de grabación de todo el mundo. Además, el control remoto con un solo botón y el cable plano sin enredos le permiten controlar la reproducción de la música y responder a llamadas sobre la marcha con un micrófono integrado. Todo ello hace que los JBL TUNE110 sean su compañero diario en el trabajo, en el hogar y de un lado a otro.",
    },
    {
        "img": "https://www.jbl.com.ar/dw/image/v2/AAUJ_PRD/on/demandware.static/-/Sites-masterCatalog_Harman/default/dw222cc677/01.JBL_Tune%20520BT_Product%20Image_Hero_Blue.png?sw=537&sfrm=png",
        "title": "JBL Tune 520BT",
        "type": "headphone",
        "price": 91000,
        "description": "Auriculares inalámbricos supraaurales",
        "stock": 23,
        "full_desc_title": "Auriculares inalámbricos supraaurales con sonido JBL Pure Bass",
        "full_desc_content": "Los auriculares JBL Tune 520BT transmiten el potente sonido JBL Pure Bass gracias a la última tecnología 5.3 BT. Estos auriculares, muy fáciles de usar, ofrecen hasta 57 horas de puro placer auditivo y 3 horas adicionales de batería con solo 5 minutos de carga. Descarga la aplicación gratuita JBL Headphones y personaliza tu sonido a través del ecualizador, las indicaciones de voz te ayudarán a conocer las prestaciones de los auriculares. Gestiona las llamadas, el sonido y el volumen desde el auricular, todo ello con el cómodo control de botones. Si recibes una llamada mientras estás viendo un vídeo en otro dispositivo, los auriculares JBL Tune 520BT se conectan fácilmente a tu móvil para que nunca pierdas una llamada. Los auriculares JBL Tune 520BT son ligeros y cómodos incluso después de horas de escucha, y puedes plegarlos para llevártelos en tu mochila a todas partes.",
    },
    {
        "img": "https://www.jbl.com.ar/dw/image/v2/AAUJ_PRD/on/demandware.static/-/Sites-masterCatalog_Harman/default/dw0e032d7c/JBL_PARTYBOX_ENCORE_ESSENTIAL_HERO_1605x1605px.png?sw=537&sfrm=png",
        "title": "JBL Partybox Encore Essential",
        "type": "speaker",
        "price": 846,
        "description": "Altavoz para fiestas portátil con sonido potente de 100W",
        "stock": 33,
        "full_desc_title": "Empieza la fiesta con un potente sonido y un juego de luces dinámico",
        "full_desc_content": "Lleva una dimensión totalmente nueva a cualquier fiesta con los exclusivos anillos de luces LED dinámicos, sincronizados con el potente sonido y los bajos profundos del PartyBox 110. Llévate el PartyBox dondequiera que vayas con el diseño a prueba de salpicaduras y conecta una guitarra y un micrófono para disfrutar de la experiencia inmersiva definitiva. Con un amplificador de bajos y el potente sonido JBL Original Pro, tus amigos no solo escucharán la música, sino que la sentirán durante 12 horas de reproducción para que la fiesta siga durante todo el día o la noche. Utiliza la aplicación PartyBox para tener un control total mientras transmites tus canciones de forma inalámbrica.",
    },
    {
        "img": "https://www.jbl.com.ar/dw/image/v2/AAUJ_PRD/on/demandware.static/-/Sites-masterCatalog_Harman/default/dw4af64bd4/1_JBL_PARTYBOX_710_HERO_0031_x8.png?sw=537&sfrm=png",
        "title": "JBL Partybox 710",
        "type": "speaker",
        "price": 1980,
        "description": "Altavoz para fiestas con un potente sonido de 800 W RMS",
        "stock": 15,
        "full_desc_title": "El alma de cualquier fiesta",
        "full_desc_content": "El PartyBox 710 a prueba de salpicaduras transformará tu próximo evento en una fiesta, un concierto o una auténtica discoteca. Con un exclusivo y colorido espectáculo de luces sincronizado con el sonido JBL Original Pro. Los controles minimalistas e intuitivos del panel superior y la aplicación PartyBox te permiten crear experiencias musicales y visuales de alto nivel. Personaliza las luces estroboscópicas e intermitentes, así como del increíble sonido del conjunto doble de altavoces de agudos y de graves. El sonido True Wireless de un solo botón empareja al instante dos PartyBox 710 para montar una fiesta aún más grande. Y con una cómoda asa y unas ruedas robustas, podrás disfrutar de los buenos momentos en cualquier lugar.",
    },
    {
        "img": "https://www.jbl.com.ar/dw/image/v2/AAUJ_PRD/on/demandware.static/-/Sites-masterCatalog_Harman/default/dw1a4b6cea/JBL_CLIP4_HERO_STANDARD_BLUE_0741_x1.png?sw=537&sfrm=png",
        "title": "JBL Clip 4",
        "type": "speaker",
        "price": 105,
        "description": "Altavoz ultraportátil resistente al agua",
        "stock": 0,
        "full_desc_title": "Clip and Play",
        "full_desc_content": "Guay, portátil y resistente al agua. El vibrante y moderno JBL Clip 4 ofrece sonido JBL Pro original increíblemente rico en un formato compacto. La forma ovalada única se adapta fácilmente a la mano. Totalmente revestido en tejidos coloridos con detalles expresivos inspirados en la moda urbana actual, es fácil combinarlo con tu estilo. El mosquetón totalmente integrado se engancha al instante a bolsas, cinturones o hebillas, para que te puedas llevar tus canciones favoritas a cualquier parte. Resistente al agua y al polvo y con hasta 10 horas de tiempo de reproducción, es lo suficientemente resistente como para llevarlo a cualquier lugar.",
    },
    {
        "img": "https://www.jbl.com.ar/dw/image/v2/AAUJ_PRD/on/demandware.static/-/Sites-masterCatalog_Harman/default/dwd57eab28/JBL_GO_3_HERO_BLACK_0079.png?sw=537&sfrm=png",
        "title": "JBL Go 3 ",
        "type": "speaker",
        "price": 78,
        "description": "Altavoz portátil a prueba de agua",
        "stock": 40,
        "full_desc_title": "Listo para llevar y usar",
        "full_desc_content": "El JBL Go 3 presenta un estilo llamativo y un sonido JBL Pro pleno y sofisticado. Con su llamativo nuevo diseño vanguardista, tejidos coloridos y detalles expresivos, es el accesorio imprescindible para tu próxima salida. Vibrarás al son de tu música con el sonido JBL Pro. Resistente al polvo y al agua conforme a la norma IP67, para que puedas seguir disfrutando llueva o haga sol, y con su asa integrada para que puedas llevarlo a cualquier parte. El Go 3 viene en tonos y combinaciones de colores completamente nuevos inspirados en la actual moda urbana. El JBL Go 3 tiene una apariencia tan vívida como su calidad de sonido.",
    },
    {
        "img": "https://www.jbl.com.ar/dw/image/v2/AAUJ_PRD/on/demandware.static/-/Sites-masterCatalog_Harman/default/dw6a972799/JBLBar1000_WEB_HERO.png?sw=537&sfrm=png",
        "title": "JBL BAR 1000",
        "type": "home_theater",
        "price": 2610,
        "description": "Barra de sonido con canales 7.1.4, altavoces envolventes desmontables, MultiBeam™",
        "stock": 2,
        "full_desc_title": "Barra de sonido con canales 7.1.4, altavoces envolventes desmontables, MultiBeam™",
        "full_desc_content": "Sumérgete en el sonido 3D con calidad teatral. Con dos unidades con salida superior en la barra principal y dos más en los altavoces extraíbles, la JBL Bar 1000 ofrece un auténtico sonido Dolby Atmos y DTS:X junto con MultiBeam para una experiencia de sonido envolvente 3D mejorada",
    },
    {
        "img": "https://tienda.personal.com.ar/images/720/webp/Microfono_inalambrico_JBL_Quantum_Stream_6e2e80ba94.png",
        "title": "JBL Quantum Stream Wireless USB-C",
        "type": "gamer",
        "price": 342,
        "description": "Micrófono inalámbrico portátil para streaming con conexión a USB-C",
        "stock": 20,
        "full_desc_title": "Llévate tu espectáculo vayas donde vayas El contenido está en todas partes.",
        "full_desc_content": "Graba, transmite y crea contenido desde cualquier lugar. El JBL Quantum Stream Wireless con dongle USB-C para dispositivos Android y los últimos Apple* es un micrófono versátil y ágil con un patrón omnidireccional que capta sonido de alta calidad desde cualquier dirección. Su diseño ligero y con cierre de clip es cómodo y práctico. Además, sigue ofreciendo grabaciones nítidas con cancelación de ruido ambiental ajustable y los opcionales filtros de fibra para entornos con viento. La ganancia ajustable del micrófono facilita la grabación en cualquier entorno y el botón para silenciar con un indicador LED evitará que te olvides de que el micrófono está encendido. Además, es compatible con la potente aplicación JBL Headphones, para que puedas personalizar completamente tu sonido. Llévate tu espectáculo vayas donde vayas con JBL Quantum Stream Wireless. * Compatible con iPhone 15",
    },
    {
        "img": "https://www.jbl.com.ar/dw/image/v2/AAUJ_PRD/on/demandware.static/-/Sites-masterCatalog_Harman/default/dwaf3d5c8b/JBL_PartyBox_310_Hero_0176_x3.png?sw=537&sfrm=png",
        "title": "JBL Partybox 310",
        "type": "speaker",
        "price": 1300,
        "description": "Altavoz portátil para fiestas con ilumniación y el pontente sonido de 240W",
        "stock": 11,
        "full_desc_title": "El increíble sonido JBL con un deslumbrante show de luces",
        "full_desc_content": "Su contundente sonido, deslumbrante iluminación e increíble potencia hacen que este altavoz destaque sobre la multitud. El JBL PartyBox 310 incluye toda la fiesta en un equipo transportable y a prueba de salpicaduras sin rival. Llega y haz sonar tus listas de reproducción favoritas en cualquier lugar, desde encuentros informales en casa a fiestas con baile en la playa. Sube las vibraciones de la fiesta con 240 vatios de sonido JBL Pro y un show de luces sincronizado que marcha al ritmo de la música. Ponte en marcha y haz que la diversión dure toda la noche o acude a la fogata y aprovecha sus impresionantes 18 horas de duración de batería. Empieza la fiesta con el JBL PartyBox 310.",
    },
    {
        "img": "https://www.jbl.com.ar/dw/image/v2/AAUJ_PRD/on/demandware.static/-/Sites-masterCatalog_Harman/default/dw9d476192/1_JBL_GO_ESSENTIAL_HERO_BLUE_31573_x1.png?sw=537&sfrm=png",
        "title": "JBL Go Essential",
        "type": "speaker",
        "price": 59,
        "description": "Altavoz pórtatil a prueba de agua",
        "stock": 14,
        "full_desc_title": "Listo para llevar y usar",
        "full_desc_content": "JBL GO Essential es un altavoz con Bluetooth portátil y ultracompacto. Reproduzca música en streaming a través de Bluetooth con una autonomía de hasta 5 horas y calidad de sonido JBL Pro original. Olas de entretenimiento con su diseño resistente al agua conforme a la norma IPX7. Disponible en 3 llamativos colores, el GO Essential es el altavoz perfecto para llevar tu música a todas partes.",
    },
    {
        "img": "https://www.jbl.com.ar/dw/image/v2/AAUJ_PRD/on/demandware.static/-/Sites-masterCatalog_Harman/default/dw1d1e7eed/JBL_Quantum_Stream_Studio_ProductImage_Hero.png?sw=537&sfrm=png",
        "title": "JBL Quantum Stream Studio",
        "type": "gamer",
        "price": 239,
        "description": "Micrófono USB para streaming",
        "stock": 10,
        "full_desc_title": "El sonido de la supervivencia Que se escuche tu voz",
        "full_desc_content": "Suena como un profesional con el micrófono de estudio JBL Quantum Stream. Tanto si estás jugando, eres un streamer o si grabas con un copresentador o con una sala llena de invitados, puedes cambiar rápidamente entre cuatro patrones de captación diferentes para que se escuche a todos los invitados. No es necesario ningún equipo adicional para mejorar tu experiencia de juego. Siempre sabrás lo alto que está sonando todo gracias al medidor VU RGB, y el compresor de rango dinámico garantiza que la voz de todos se mantenga al mismo nivel. ¿Vas a retransmitir una partida? Controla totalmente el equilibrio entre los sonidos de la partida y sus propios comentarios. Utiliza el software para PC JBL QuantumENGINE incluido para ajustar el ecualizador, aplicar reducción de ruido o personalizar la radiante iluminación RGB del micrófono.",
    },
    {
        "img": "https://www.jbl.com.ar/dw/image/v2/AAUJ_PRD/on/demandware.static/-/Sites-masterCatalog_Harman/default/dw692cfc40/JBL_QUANTUM_610_Product%20Image_Hero_CES.png?sw=537&sfrm=png",
        "title": "JBL Quantum 610 Wireless",
        "type": "gamer",
        "price": 325,
        "description": "Auriculares integrales para gaming sin cables",
        "stock": 68,
        "full_desc_title": "El sonido de la supervivencia.",
        "full_desc_content": "Es hora de subir de nivel con JBL Quantum 610 Wireless. JBL QuantumSURROUND ofrece una experiencia totalmente inmersiva. Además, los drivers de 50 mm con JBL QuantumSOUND SIGNATURE hacen que cada momento sea épico, tanto si estás en una misión sigilosa como en el calor de una batalla masiva. Tu voz sonará alta y clara con el micrófono de asta abatible, y puedes trazar y elaborar estrategias con tu equipo en DISCORD, Skype y TeamSpeak. Disfruta de más horas de juego con las 40 horas de autonomía de la batería o conéctalo para sesiones sin fin con el cable de carga USB.",
    },
    {
        "img": "https://www.jbl.com.ar/dw/image/v2/AAUJ_PRD/on/demandware.static/-/Sites-masterCatalog_Harman/default/dw34970341/1.JBL_QUANTUM_910_Wireless_Product%20Image_Hero%20Mic%20Down.png?sw=537&sfrm=png",
        "title": "JBL Quantum 910 Wireless",
        "type": "gamer",
        "price": 525,
        "description": "Auriculares inalámbricos para gaming de alto rendimiento",
        "stock": 54,
        "full_desc_title": "El sonido de la supervivencia",
        "full_desc_content": "¿Esas voces están detrás de ti? ¿Esos pasos vienen por la izquierda? Escuchar lo que te rodea es crucial y un sonido verdaderamente envolvente te da la ventaja que solo ofrecía un auricular con cable. Hasta ahora. Los auriculares JBL Quantum 910 Wireless ofrecen un sonido de alta resolución, espacial y dual con seguimiento de cabeza integrado para estar siempre en el centro de la acción. La conexión inalámbrica de baja latencia evita los retrasos al hablar con el equipo mientras que la cancelación de ruido activa te permite jugar sin distracciones incluso en los lugares más ruidosos. Los Quantum 910 inalámbricos ofrecen hasta 39 horas de batería, pero puedes cargarlos mientras juegas durante las sesiones más largas. Y con una comodidad ergonómica sin igual, las sesiones van a ser largas, seguro. Corta el cordón y juega a tu manera.",
    },
    {
        "img": "https://www.jbl.com.ar/dw/image/v2/AAUJ_PRD/on/demandware.static/-/Sites-masterCatalog_Harman/default/dwd70387e8/JBL_Quantum_300_Product%20Image_Hero.png?sw=537&sfrm=png",
        "title": "JBL Quantum 300",
        "type": "gamer",
        "price": 125,
        "description": "Auriculares integlares hibridos para gaming en PC con cable",
        "stock": 30,
        "full_desc_title": "Sound is Survival",
        "full_desc_content": "Lleve su juego a otro nivel con un sonido superior. Los JBL Quantum 300 con cable ofrecen un entorno inmersivo gracias al sistema JBL QuantumSOUND Signature y a un preciso posicionamiento de audio. JBL QuantumSURROUND™ genera un espacio sonoro envolvente que le aporta una ventaja en el juego y maximiza su rendimiento. La diadema ligera y las almohadillas de espuma viscoelástica harán que se sienta cómodo en todo momento. Un micrófono vocal de asta abatible facilita la comunicación tanto con aliados como con enemigos.",
    },
    {
        "img": "https://www.jbl.com.ar/dw/image/v2/AAUJ_PRD/on/demandware.static/-/Sites-masterCatalog_Harman/default/dw1823f3d7/1.JBL_CINEMA_SB120_HERO_REFLECTIONS_0036_x1.png?sw=537&sfrm=png",
        "title": "JBL Cinema SB120",
        "type": "home_theater",
        "price": 358,
        "description": "Barra de sonido de 2.0 sin cables",
        "stock": 35,
        "full_desc_title": "Simple. Compacta. Potente.",
        "full_desc_content": "La JBL Cinema SB120 es una barra de sonido de perfil bajo que encaja perfectamente frente al televisor. Incluye Bluetooth para que disfrutes de la música sin cables y conexión HDMI ARC para una experiencia de usuario simplificada. Combina 110 W de potencia, dos altavoces de gama completa y dos altavoces de graves de 2,5 incorporados en la barra, un subwoofer incorporado para graves profundos y Dolby digital para ofrecerte la mejor experiencia auditiva.",
    },
    {
        "img": "https://www.jbl.com.ar/dw/image/v2/AAUJ_PRD/on/demandware.static/-/Sites-masterCatalog_Harman/default/dw3522be14/JBLBar800_WEB_HERO.png?sw=537&sfrm=png",
        "title": "JBL BAR 800",
        "type": "home_theater",
        "price": 988,
        "description": "Barra de sonido con canales 5.1.2, altavoces envolventes desmontables y Dolby Atmos®",
        "stock": 8,
        "full_desc_title": "Un auténtico sonido envolvente Dolby Atmos®",
        "full_desc_content": "Sumérgete e el sonido 3D con calidad teatral. Con unidades con salida superior, la JBL Bar 800 ofrece un auténtico sonido envolvente 3D Dolby Atmos®",
    },
    {
        "img": "https://www.jbl.com.ar/dw/image/v2/AAUJ_PRD/on/demandware.static/-/Sites-masterCatalog_Harman/default/dw2a888357/1_JBL_CHARGE_ESSENTIAL_2_HERO_31487_x1.png?sw=537&sfrm=png",
        "title": "JBL Charge Essential 2",
        "type": "speaker",
        "price": 284,
        "description": "Altavoz portátil resistente al agua con batería integrada",
        "stock": 0,
        "full_desc_title": "Reproducción y carga infinitas",
        "full_desc_content": "Lleva la fiesta contigo haga el tiempo que haga. El altavoz JBL Charge Essential 2 ofrece el potente sonido JBL Original Pro. Hasta 20 horas de autonomía y una práctica batería integrada que te permite cargar tus dispositivos y alargar la fiesta durante toda la noche. ¿Llueve? ¿Has derramado la bebida? Con un diseño resistente al agua conforme a la norma IPX7, el Charge Essential 2 aguanta lo que le eches.",
    },
    {
        "img": "https://www.jbl.com.ar/dw/image/v2/AAUJ_PRD/on/demandware.static/-/Sites-masterCatalog_Harman/default/dw22b7eb04/1_JBL_BOOMBOX_3_SQUAD_HERO_33262_x2.png?sw=537&sfrm=png",
        "title": "JBL Boombox 3 Special",
        "type": "speaker",
        "price": 899,
        "description": "Altavoz portátil",
        "stock": 5,
        "full_desc_title": "Sonido arrollador. Durante todo el día.",
        "full_desc_content": "Hemos mejorado aún más nuestro altavoz Bluetooth portátil más potente. La icónica silueta del JBL Boombox 3 presenta una nueva y atrevida versión con un resistente asa de metal y empuñaduras de silicona, dos tapas laterales y un tejido resistente al agua y al polvo. También se ha rediseñado el interior, con un nuevo subwoofer que ofrece graves mucho más profundos y el arrollador JBL Original Pro Sound, todo ello con menor distorsión. Gracias a las 24 horas de tiempo de reproducción, podrá acompañarte desde el entrenamiento de la mañana hasta la cita nocturna con tus amigos. Y para disfrutar de un sonido prácticamente ilimitado, puedes conectar varios altavoces con la aplicación JBL Portable.",
    },
    {
        "img": "https://www.jbl.com.ar/dw/image/v2/AAUJ_PRD/on/demandware.static/-/Sites-masterCatalog_Harman/default/dw69e549c3/1_JBL_BOOMBOX_3_HERO_BLACK_33216_x2.png?sw=537&sfrm=png",
        "title": "JBL Boombox 3 Standard",
        "type": "speaker",
        "price": 891,
        "description": "Altavoz portátil",
        "stock": 11,
        "full_desc_title": "Sonido arrollador. Durante todo el día.",
        "full_desc_content": "Hemos mejorado aún más nuestro altavoz Bluetooth portátil más potente. La icónica silueta del JBL Boombox 3 presenta una nueva y atrevida versión con un resistente asa de metal y empuñaduras de silicona, dos tapas laterales y un tejido resistente al agua y al polvo. También se ha rediseñado el interior, con un nuevo subwoofer que ofrece graves mucho más profundos y el arrollador JBL Original Pro Sound, todo ello con menor distorsión. Gracias a las 24 horas de tiempo de reproducción, podrá acompañarte desde el entrenamiento de la mañana hasta la cita nocturna con tus amigos. Y para disfrutar de un sonido prácticamente ilimitado, puedes conectar varios altavoces con la aplicación JBL Portable.",
    },
    {
        "img": "https://www.jbl.com.ar/dw/image/v2/AAUJ_PRD/on/demandware.static/-/Sites-masterCatalog_Harman/default/dw376d0d85/JBL_CLIP_5_HERO_RED_48132_x4.jpg?sw=270&sh=330&sm=fit&sfrm=png",
        "title": "JBL Clip 5",
        "type": "speaker",
        "price": 128,
        "description": "Altavoz ultraportátil resistente al agua",
        "stock": 0,
        "full_desc_title": "Clip and Play",
        "full_desc_content": "El altavoz Bluetooth ultraportátil JBL Clip 5 es lo suficientemente pequeño como para llevarlo en una mano, pero que no te engañe su tamaño: es grande donde de verdad importa. Un mosquetón ancho y totalmente integrado permite engancharlo a casi cualquier cosa. El potente amplificador y el radiador pasivo ofrecen un sonido JBL Pro más alto y potente, así como unos graves contundentes. Una sola carga te ofrece hasta 12 horas de reproducción e incluso más si Playtime Boost está activado. Su certificación IP67 confirma su resistencia al agua y al polvo, por lo que estará encantado de acompañarte en tu próxima excursión o acampada. Combina dos Clip 5 para obtener un sonido estéreo o conéctalo al instante con varios altavoces compatibles mediante JBL Auracast para obtener un sonido aún mayor en más espacio. Además, está disponible en varios colores, para que encuentres siempre uno que se adapte a tu estilo. Con el JBL Clip 5, cada día es una aventura.",
    },
    {
        "img": "https://www.jbl.com.ar/dw/image/v2/AAUJ_PRD/on/demandware.static/-/Sites-masterCatalog_Harman/default/dw80dc6d3f/JBL_QUANTUM_DUO_HERO_V2_011_Main_x2.jpg?sw=270&sh=330&sm=fit&sfrm=png",
        "title": "JBL Quantum Duo",
        "type": "gamer",
        "price": 346,
        "description": "Altavoces para Gaming en PC",
        "stock": 55,
        "full_desc_title": "El sonido de la supervivencia",
        "full_desc_content": "Sube de nivel con los potentes altavoces JBL Quantum Duo. Métete de lleno en la acción con un sonido en perfecta sintonía y unos efectos de luz únicos. Identifica los ataques de fuego, escucha a tus enemigos acechándote y vive la acción. Con el sonido envolvente de JBL y la tecnología Dolby Digital en un diseño moderno e inconfundible. No te pierdas ni un solo detalle con los amplificadores y los altavoces de agudos, que garantizan una nitidez de sonido increíble. Con distintos valores predeterminados de colores y patrones de iluminación para personalizar, sentirás los juegos más reales que nunca.",
    },
    {
        "img": "https://www.jbl.com.ar/dw/image/v2/AAUJ_PRD/on/demandware.static/-/Sites-masterCatalog_Harman/default/dw31ff690b/1.JBL_ENDURANCE_RACE_TWS_Product%20Image_Hero_Black.png?sw=537&sfrm=png",
        "title": "JBL Endurance Race TWS",
        "type": "headphone",
        "price": 135,
        "description": "Auriculares de botón deportivos impermeables",
        "stock": 28,
        "full_desc_title": "Un diseño duradero y perfecto para adaptarse a tu vida activa",
        "full_desc_content": "Los auriculares de botón activos JBL Endurance Race True Wireless están siempre preparados. Con 30 horas de batería y un diseño resistente al agua y al polvo, ofrecen el mejor sonido JBL Pure Bass con una gran comodidad durante todo el día. El ajuste resistente y superior te permite estar siempre activo, desde la playa hasta la sala de reuniones, gracias a su diseño sellado y estable. Pregunta a tu asistente de voz preferido, gestiona el audio y realiza llamadas perfectas con solo tocar un botón. Y cuando necesites escuchar lo que te rodeas, hazlo con un sonido ambiental mejorado.",
    },
    {
        "img": "https://www.jbl.com.ar/dw/image/v2/AAUJ_PRD/on/demandware.static/-/Sites-masterCatalog_Harman/default/dw552ef2dc/1.JBL_Live%20Pro%202_Product%20image_Hero_White.png?sw=537&sfrm=png",
        "title": "JBL Live Pro 2 TWS Silver",
        "type": "headphone",
        "price": 286,
        "description": "Auriculares True Wireless con cancelación de ruido",
        "stock": 58,
        "full_desc_title": "Para escuchar y que te escuchen. En cualquier lugar y en cualquier momento.",
        "full_desc_content": "Disfruta durante todo el día de estos compañeros de trabajo y de ocio llenos de estilo. Los auriculares JBL Live Pro 2 ofrecen hasta 40 horas del increíble sonido emblemático de JBL (10 horas en los auriculares + 30 horas en el estuche), carga rápida y carga inalámbrica compatible con Qi para cuando necesites un extra de batería. True Adaptive Noise Cancelling elimina las distracciones para ofrecerte un sonido totalmente envolvente, mientras que Smart Ambient te mantiene al tanto de lo que pasa a tu alrededor. El diseño de barra cerrada con tubos ovalados asegura una mejor cancelación de ruido y una mayor calidad de audio para los que prefieren una estética más limpia. ¿Tienes que hablar? Haz llamadas claras y perfectas con seis micrófonos de haz o conecta con tu asistente de voz preferido y disfruta de un control total manos libres, estés donde estés.",
    },
    {
        "img": "https://www.jbl.com.ar/dw/image/v2/AAUJ_PRD/on/demandware.static/-/Sites-masterCatalog_Harman/default/dw888b72f8/1_JBL_FLIP6_HERO_BLACK_29391_x2.png?sw=537&sfrm=png",
        "title": "JBL Flip 6",
        "type": "speaker",
        "price": 250,
        "description": "Altavoz portátil a prueba de agua",
        "stock": 55,
        "full_desc_title": "El mejor sonido para cualquier aventura",
        "full_desc_content": "La banda sonora de tus aventuras El atrevido JBL Flip 6 ofrece el potente sonido JBL Original Pro con una claridad excepcional gracias a su sistema de altavoces bidireccionales, con un driver optimizado en forma de pista de carreras, un altavoz de agudos independiente y dos radiadores pasivos (uno a cada lateral). Este altavoz, además de ofrecerte el mejor sonido, es fácil de transportar y es resistente al agua y al polvo, por lo que puedes llevarlo a cualquier parte, sin importar el tiempo que haga. Y con 12 horas de batería, puedes irte de fiesta desde el amanecer al anochecer, allá donde te lleve la música. Usa PartyBoost para conectar varios altavoces compatibles. El Flip 6 está disponible en una gran variedad de colores.",
    },
    {
        "img": "https://www.jbl.com.ar/dw/image/v2/AAUJ_PRD/on/demandware.static/-/Sites-masterCatalog_Harman/default/dw233bb611/1.JBL_Quantum%20TWS_Product%20Image_Hero.png?sw=537&sfrm=png",
        "title": "JBL Quantum TWS",
        "type": "gamer",
        "price": 260,
        "description": "Auriculares True Wireless para gaming con cancelación de ruido",
        "stock": 67,
        "full_desc_title": "El sonido de la supervivencia",
        "full_desc_content": "Reproduce contenido en cualquier lugar y oye todo lo que pasa con JBL Quantum TWS. La cancelación de ruido adaptable True Adaptive limita las distracciones mientras te sumerges en un sonido envolvente y preciso. Si necesitas volver al mundo real, JBL Dual Source te permite pasar del audio del juego a las llamadas entrantes de forma rápida y sencilla, mientras que Ambient Aware te mantiene al tanto de lo que te rodea. Compatible con todas las fuentes Bluetooth, la transición entre dispositivos es perfecta vayas donde vayas. Conecta fácilmente con smartphones con Bluetooth y establece conexiones de baja latencia de 2,4 GHz a dispositivos compatibles gracias al dongle USB-C incluido en un estuche de carga que añade 16 horas de energía a las 8 que ofrecen auriculares.",
    }
];

arrayProductos.forEach(item => console.log(item.type));